//obtenemos toda la funcionalidad del modelo shop
var ENCUESTA = require('./encuesta');

ENCUESTA.modulosTable();
ENCUESTA.preguntasTable();
ENCUESTA.respuestasTable();
ENCUESTA.encuesta_respuestasTable();

//Agregar modulos

	ENCUESTA.insertModulo(
    {
	    idmodulo:0,
	    nombre:"Modulo de datos personales",
	    esinicial:1
    });


	ENCUESTA.insertModulo(
    {
	    idmodulo:1,
	    nombre:"Módulo de ingresos",
	    esinicial:0
    });


	ENCUESTA.insertModulo(
    {
	    idmodulo:2,
	    nombre:"Modulo Universitario",
	    esinicial:0
    });


//Agregar preguntas
	ENCUESTA.insertPregunta(
    {
        idpregunta:0,
        pregunta:"¿Cúal es su nombre?",
        modulo:0,
        espreguntainicial:1,
        tipo:0,
        siguientepregunta:1,
        siguientemodulo:-1
    }
);
	ENCUESTA.insertPregunta(
    {
        idpregunta:1,
        pregunta:"¿Cúal es su edad?",
        modulo:0,
        espreguntainicial:0,
        tipo:1,
        siguientepregunta:-1,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:0,
       respuesta:"18 años o más",
       pregunta:1,
       siguientepregunta:2,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:1,
       respuesta:"Menos de 18 años",
       pregunta:1,
       siguientepregunta:4,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:2,
        pregunta:"¿Cúal es su estado civil?",
        modulo:0,
        espreguntainicial:0,
        tipo:1,
        siguientepregunta:-1,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:2,
       respuesta:"Casado",
       pregunta:2,
       siguientepregunta:3,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:3,
       respuesta:"Soltero",
       pregunta:2,
       siguientepregunta:4,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:4,
       respuesta:"Unión libre",
       pregunta:2,
       siguientepregunta:3,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:3,
        pregunta:"¿Hace cuanto vive con su pareja?",
        modulo:0,
        espreguntainicial:0,
        tipo:1,
        siguientepregunta:4,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:5,
       respuesta:"Menos de 2 años",
       pregunta:3,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:6,
       respuesta:"2 años o más",
       pregunta:3,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:4,
        pregunta:"¿Cúal es su grado de escolaridad?",
        modulo:0,
        espreguntainicial:0,
        tipo:1,
        siguientepregunta:-1,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:7,
       respuesta:"Bachiller",
       pregunta:4,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:8,
       respuesta:"Técnico",
       pregunta:4,
       siguientepregunta:-1,
       siguientemodulo:1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:9,
       respuesta:"Tecnólogo",
       pregunta:4,
       siguientepregunta:-1,
       siguientemodulo:1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:10,
       respuesta:"Universitario",
       pregunta:4,
       siguientepregunta:-1,
       siguientemodulo:2,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:11,
       respuesta:"Postgrado",
       pregunta:4,
       siguientepregunta:-1,
       siguientemodulo:2,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:5,
        pregunta:"¿Cáules son sus ingresos mensuales?",
        modulo:1,
        espreguntainicial:1,
        tipo:1,
        siguientepregunta:-1,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:12,
       respuesta:"Menos de un salario mínimo",
       pregunta:5,
       siguientepregunta:7,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:13,
       respuesta:"Un salario mínimo",
       pregunta:5,
       siguientepregunta:7,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:14,
       respuesta:"Más de un salario mínimo",
       pregunta:5,
       siguientepregunta:6,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:6,
        pregunta:"¿Cuántos trabajos tiene?",
        modulo:1,
        espreguntainicial:0,
        tipo:1,
        siguientepregunta:-1,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:15,
       respuesta:"1",
       pregunta:6,
       siguientepregunta:8,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:16,
       respuesta:"2",
       pregunta:6,
       siguientepregunta:8,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:17,
       respuesta:"Más de 2",
       pregunta:6,
       siguientepregunta:8,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:7,
        pregunta:"¿Usted es trabajador independiente?",
        modulo:1,
        espreguntainicial:0,
        tipo:1,
        siguientepregunta:-1,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:18,
       respuesta:"Si",
       pregunta:7,
       siguientepregunta:9,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:19,
       respuesta:"No",
       pregunta:7,
       siguientepregunta:8,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:8,
        pregunta:"Su/sus contrato/s es/son",
        modulo:1,
        espreguntainicial:0,
        tipo:2,
        siguientepregunta:-1,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:20,
       respuesta:"A termino fijo",
       pregunta:8,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:21,
       respuesta:"Prestación de servicios",
       pregunta:8,
       siguientepregunta:9,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:22,
       respuesta:"A término indefinido",
       pregunta:8,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:9,
        pregunta:"¿Cotiza salud y pensión?",
        modulo:1,
        espreguntainicial:0,
        tipo:1,
        siguientepregunta:-1,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:23,
       respuesta:"Si",
       pregunta:9,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:24,
       respuesta:"No",
       pregunta:9,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:10,
        pregunta:"¿Cuántos años estudió en la universidad?",
        modulo:2,
        espreguntainicial:1,
        tipo:1,
        siguientepregunta:11,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:25,
       respuesta:"4 años",
       pregunta:10,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:26,
       respuesta:"Más de 4 años y menos de 8",
       pregunta:10,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:27,
       respuesta:"8 años o más",
       pregunta:10,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:11,
        pregunta:"Estudio en una Universidad:",
        modulo:2,
        espreguntainicial:0,
        tipo:2,
        siguientepregunta:-1,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:28,
       respuesta:"Pública",
       pregunta:11,
       siguientepregunta:12,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:29,
       respuesta:"Privada",
       pregunta:11,
       siguientepregunta:13,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:30,
       respuesta:"Privada y pública",
       pregunta:11,
       siguientepregunta:12,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:12,
        pregunta:"¿Usted terminó todos sus estudios?",
        modulo:2,
        espreguntainicial:0,
        tipo:1,
        siguientepregunta:14,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:31,
       respuesta:"Si",
       pregunta:12,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:32,
       respuesta:"No",
       pregunta:12,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:13,
        pregunta:"¿Usted pagó?",
        modulo:2,
        espreguntainicial:0,
        tipo:1,
        siguientepregunta:12,
        siguientemodulo:-1
    }
);
ENCUESTA.insertRespuesta(
	{
       idrespuesta:33,
       respuesta:"Menos de un millon",
       pregunta:13,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:34,
       respuesta:"Más de un millon y menos de 4 millones",
       pregunta:13,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
ENCUESTA.insertRespuesta(
	{
       idrespuesta:35,
       respuesta:"Más de 4 millones",
       pregunta:13,
       siguientepregunta:-1,
       siguientemodulo:-1,
	}
);	
	ENCUESTA.insertPregunta(
    {
        idpregunta:14,
        pregunta:"¿Cúal es el nombre de su universidad?",
        modulo:2,
        espreguntainicial:0,
        tipo:0,
        siguientepregunta:-1,
        siguientemodulo:1
    }
);
